/* One catalog feeds product pages, search, comparison and the persistent cart. */
window.RP = (() => {
 const L=(ru,en,zh)=>({ru,en,zh});
 const specs={weight:L('Масса с батареей','Weight with battery','含电池重量'),height:L('Высота','Height','高度'),dof:L('Степени свободы','Degrees of freedom','自由度'),runtime:L('Время работы, примерно','Typical battery life','续航时间（约）'),vision:L('Система восприятия','Perception','感知系统'),connection:L('Связь','Connectivity','连接'),size:L('Размеры стоя','Standing dimensions','站立尺寸'),speed:L('Скорость','Speed','速度'),slope:L('Подъём','Climbing angle','爬坡角度'),battery:L('Батарея','Battery','电池'),dev:L('Вторичная разработка','Secondary development','二次开发'),display:L('Экран','Display','显示屏'),camera:L('Камера','Camera','摄像头')};
 const edu=L('Доступна в версии EDU','Available in EDU version','EDU 版本支持');
 const products=[
 {id:'g1',name:'Unitree G1',group:'humanoid',price:1666666,source:'https://www.unitree.com/g1/',images:['g1-0.webp','g1-1.webp','g1-2.webp','g1-3.webp'],
 tagline:L('Большие возможности. Компактный гуманоид.','Big potential. Compact humanoid.','紧凑人形，无限可能。'),
 description:L('Гуманоид с 23 степенями свободы и складной конструкцией. Для демонстраций движения; для лаборатории и собственных алгоритмов выбирайте G1 EDU.','A foldable humanoid with 23 degrees of freedom. Explore dynamic motion; choose G1 EDU for laboratory research and custom algorithms.','具有 23 个自由度的可折叠人形机器人。适合运动演示；实验室研究和自定义算法请选择 G1 EDU。'),
 paragraphs:[L('G1 сочетает подвижные руки, ноги и корпус в платформе высотой 132 см. Складная конструкция облегчает перевозку между лабораторией, учебной аудиторией и демонстрационной площадкой.','G1 combines articulated arms, legs and a torso in a 132 cm platform. Its folding structure makes transport between a lab, classroom and demonstration venue easier.','G1 将灵活的手臂、腿部和躯干集成于 132 厘米高的平台中。可折叠结构便于在实验室、教室和演示场地之间运输。'),L('Базовая модель и EDU отличаются доступом к разработке и оснащением. Ловкие кисти и дополнительные вычислители относятся к отдельным конфигурациям EDU: их нужно согласовать при подборе.','The base model and EDU differ in development access and equipment. Dexterous hands and extra computing modules belong to selected EDU configurations and should be specified when ordering.','基础版与 EDU 版的开发权限和配置不同。灵巧手和额外计算模块属于特定 EDU 配置，需在选型时确认。')],
 highlights:[['23',L('степени свободы','degrees of freedom','自由度')],['132 cm',L('высота','height','高度')],['≈35 kg',L('масса','weight','重量')]],
 specs:[['height','132 cm'],['weight','≈35 kg'],['dof','23'],['runtime',L('Около 2 часов','About 2 hours','约 2 小时')],['vision','3D LiDAR + Intel RealSense D435'],['connection','Wi-Fi 6 / Bluetooth 5.2'],['dev',edu]],
 features:[L('Складная конструкция','Foldable design','可折叠结构'),L('Объёмное восприятие','3D perception','三维感知'),L('Конфигурации EDU для R&D','EDU configurations for R&D','EDU 科研配置')],
 fit:L('Демонстрации, знакомство с гуманоидной робототехникой. Исследования и обучение алгоритмам — с подходящей комплектацией EDU.','Demonstrations and an introduction to humanoid robotics. Research and algorithm development require an appropriate EDU configuration.','适合演示及人形机器人入门。科研与算法开发需选择相应 EDU 配置。')},
 {id:'r1',name:'Unitree R1',group:'humanoid',price:1666666,source:'https://www.unitree.com/mobile/R1/',images:['r1-cover.webp','r1-0.webp','r1-1.webp','r1-2.webp','r1-3.webp'],
 tagline:L('Лёгкость в каждом движении.','Movement, made lighter.','轻巧身形，灵活运动。'),
 description:L('Компактный гуманоид высотой 123 см: 26 степеней свободы, бинокулярная камера и масса около 29 кг в версии R1.','A compact 123 cm humanoid with 26 degrees of freedom, a binocular camera and a weight of approximately 29 kg in the R1 version.','R1 版本高 123 厘米，约重 29 公斤，拥有 26 个自由度和双目摄像头。'),
 paragraphs:[L('R1 — вариант для знакомства с двуногой робототехникой и демонстрации координированных движений. Подвижные голова и корпус дополняют руки и ноги, а микрофонный массив и камера служат для взаимодействия с окружающим миром.','R1 offers an introduction to bipedal robotics and coordinated movement demonstrations. An articulated head and waist complement the limbs; a microphone array and camera provide inputs from the surrounding environment.','R1 适合双足机器人入门及协调运动演示。可活动头部与腰部配合四肢，麦克风阵列与摄像头用于感知周围环境。'),L('Здесь указаны характеристики R1, а не R1 AIR. Вторичная разработка официально предусмотрена для R1 EDU. Доступность отдельных демонстрационных функций зависит от прошивки и конфигурации.','These specifications describe R1, not R1 AIR. Official secondary development is offered in R1 EDU. Availability of individual demonstration features depends on firmware and configuration.','此处为 R1 参数，并非 R1 AIR。官方二次开发功能由 R1 EDU 提供。具体演示功能取决于固件和配置。')],
 highlights:[['26',L('степеней свободы','degrees of freedom','自由度')],['123 cm',L('высота','height','高度')],['≈29 kg',L('масса','weight','重量')]],
 specs:[['height','123 cm'],['weight','≈29 kg'],['dof','26'],['runtime',L('Около 1 часа','About 1 hour','约 1 小时')],['camera',L('Бинокулярная','Binocular','双目摄像头')],['connection','Wi-Fi 6 / Bluetooth 5.2'],['dev',edu]],
 features:[L('Подвижные голова и корпус','Articulated head and waist','可活动头部与腰部'),L('Бинокулярная камера','Binocular camera','双目摄像头'),L('Быстросъёмная батарея','Quick-release battery','快拆电池')],
 fit:L('Технологические презентации и демонстрации. Для управления суставами собственным кодом предварительно подберите R1 EDU.','Technology presentations and demonstrations. Select R1 EDU in advance if you need to control joints with your own code.','适合科技展示与演示。如需使用自己的代码控制关节，请选择 R1 EDU。')},
 {id:'go2-air',name:'Unitree Go2 Air',group:'quadruped',price:240000,source:'https://www.unitree.com/go2/',images:['go2-cover.webp','go2-0.webp','go2-1.webp','go2-2.webp','go2-3.webp'],
 tagline:L('Первый шаг в четвероногую робототехнику.','Your first step into quadruped robotics.','开启四足机器人之旅。'),
 description:L('Начальная версия Go2: скорость до 2,5 м/с, 4D LiDAR и управление через приложение. Для знакомства с платформой и демонстраций.','The entry Go2: up to 2.5 m/s, 4D LiDAR and app control. Built for exploring the platform and demonstrations.','Go2 入门版本：最高速度 2.5 米/秒，配备 4D LiDAR，支持应用控制，适合入门体验和演示。'),
 paragraphs:[L('Четыре ноги с 12 приводами обеспечивают устойчивое движение, а широкоугольная камера и LiDAR помогают воспринимать препятствия. Air — доступная точка входа в семейство Go2 без расширенного набора функций Pro.','Four legs with 12 actuators support stable movement, while a wide-angle camera and LiDAR help perceive obstacles. Air is the entry point to the Go2 family without the extended Pro feature set.','四条腿共 12 个驱动器支持稳定运动，广角摄像头与激光雷达用于感知障碍物。Air 是 Go2 系列入门配置，不含 Pro 的扩展功能。'),L('Air не включает ISS 2.0 и официальную вторичную разработку. Если задача требует собственного ПО управления или исследовательских модулей, обсудите EDU до покупки.','Air does not include ISS 2.0 or official secondary development. If your project needs custom control software or research modules, discuss EDU before purchasing.','Air 不含 ISS 2.0 及官方二次开发支持。如项目需要自定义控制软件或科研模块，请在购买前咨询 EDU。')],
 highlights:[['2.5 m/s',L('скорость до','top speed','最高速度')],['4D',L('LiDAR','LiDAR','激光雷达')],['≈15 kg',L('масса','weight','重量')]],
 specs:[['weight','≈15 kg'],['size','70 × 31 × 40 cm'],['speed','0–2.5 m/s'],['slope','30°'],['runtime',L('1–2 часа','1–2 hours','1–2 小时')],['battery','8000 mAh'],['vision','4D LiDAR + HD camera'],['dev',edu]],
 features:[L('Управление через приложение','App control','应用控制'),L('Камера и LiDAR','Camera and LiDAR','摄像头与激光雷达'),L('12 приводов','12 joint motors','12 个关节电机')],
 fit:L('Демонстрации движения, знакомство с роботами и управление через приложение. Для SDK и R&D нужна другая комплектация.','Movement demonstrations, robotics exploration and app control. SDK and R&D projects require a different configuration.','适合运动演示、机器人入门与应用控制。SDK 和科研项目需选择其他配置。')},
 {id:'go2-pro',name:'Unitree Go2 Pro',group:'quadruped',price:350000,source:'https://www.unitree.com/go2/',images:['go2-cover.webp','go2-0.webp','go2-3.webp','go2-1.webp','go2-2.webp'],
 tagline:L('Больше динамики. Больше взаимодействия.','More motion. More interaction.','更灵活的运动，更丰富的互动。'),
 description:L('Go2 с повышенной скоростью до 3,5 м/с и системой следования ISS 2.0. Более насыщенные сценарии взаимодействия по сравнению с Air.','Go2 with a higher speed of up to 3.5 m/s and ISS 2.0 following. A broader set of interaction features than Air.','最高速度达 3.5 米/秒，支持 ISS 2.0 跟随系统，相比 Air 提供更多互动功能。'),
 paragraphs:[L('Pro добавляет к базовой платформе систему следования и более динамичное движение. Он подходит для демонстраций, мероприятий и знакомства с готовыми функциями четвероногого робота.','Pro adds a following system and more dynamic motion to the base platform. It suits demonstrations, events and exploration of a quadruped robot’s built-in features.','Pro 在基础平台上增加跟随功能及更强的运动性能，适合演示、活动展示和体验四足机器人的内置功能。'),L('Pro не равнозначен EDU: официальная вторичная разработка в этой версии не заявлена. Голосовые и сетевые функции, включая 4G, нужно проверять для региона поставки. Фотографии показывают семейство Go2.','Pro is not equivalent to EDU: official secondary development is not listed for this version. Voice and network features, including 4G, must be checked for the delivery region. Photos show the Go2 family.','Pro 并不等同于 EDU：本版本未列出官方二次开发支持。语音和 4G 等网络功能需根据交付地区确认。照片展示 Go2 系列。')],
 highlights:[['3.5 m/s',L('скорость до','top speed','最高速度')],['ISS 2.0',L('следование','following system','跟随系统')],['40°',L('подъём до','climbing angle','最大爬坡角度')]],
 specs:[['weight','≈15 kg'],['size','70 × 31 × 40 cm'],['speed','0–3.5 m/s'],['slope','40°'],['runtime',L('1–2 часа','1–2 hours','1–2 小时')],['battery','8000 mAh'],['vision','4D LiDAR + HD camera'],['dev',edu]],
 features:[L('Следование ISS 2.0','ISS 2.0 following','ISS 2.0 跟随'),L('Скорость до 3,5 м/с','Up to 3.5 m/s','最高 3.5 米/秒'),L('Расширенные готовые режимы','More built-in modes','更多内置模式')],
 fit:L('Интерактивные демонстрации, выставки и знакомство с режимами следования. Для разработки собственных алгоритмов выбирайте EDU.','Interactive demonstrations, exhibitions and following-mode exploration. Choose EDU for custom algorithm development.','适合互动演示、展览和跟随模式体验。自定义算法开发请选择 EDU。')},
 {id:'loona',name:'Loona',group:'companion',price:60000,source:'https://keyirobot.com/en-id/products/petbot',images:['loona-0.webp','loona-1.webp','loona-2.webp','loona-3.webp'],
 tagline:L('Маленький робот. Большой характер.','Small robot. Big personality.','小小机器人，大大个性。'),
 description:L('Домашний робот-компаньон с выразительным экраном, подвижными ушами, камерой и интерактивными играми.','A home robot companion with an expressive display, moving ears, a camera and interactive games.','家用陪伴机器人，拥有生动的屏幕表情、可活动耳朵、摄像头及互动游戏。'),
 paragraphs:[L('Loona перемещается на колёсах, реагирует на голос, лица и жесты. Экран и движения корпуса создают живой характер, а приложение открывает игры и занятия с визуальным программированием Blockly.','Loona moves on wheels and responds to voices, faces and gestures. Its display and body movements bring personality to life; the app provides games and Blockly visual programming activities.','Loona 通过轮子移动，对声音、人脸与手势作出反应。屏幕与身体动作塑造生动个性，应用提供游戏和 Blockly 可视化编程活动。'),L('Для онлайн-функций нужны совместимое приложение и интернет. Языки взаимодействия, подписки, зарядная станция и игровые аксессуары зависят от версии и комплекта; уточните их до заказа. Галерея производителя показывает также комплекты Premium.','Online features require a compatible app and internet. Interaction languages, subscriptions, charging dock and game accessories depend on version and bundle; confirm them before ordering. Manufacturer images also show Premium bundles.','在线功能需要兼容应用和网络。互动语言、订阅、充电座及游戏配件取决于版本和套装，请在订购前确认。官方图片也展示 Premium 套装。')],
 highlights:[['≈1.1 kg',L('масса','weight','重量')],['2.4″',L('экран','display','屏幕')],['720p',L('RGB-камера','RGB camera','RGB 摄像头')]],
 specs:[['weight','≈1.1 kg'],['display','2.4″ LCD'],['camera','720p RGB'],['vision','3D ToF'],['battery','1350 mAh / 11.1 V'],['connection','Wi-Fi 2.4 / 5.8 GHz'],['runtime',L('Около 2 часов игры','About 2 hours of play','约 2 小时游戏')]],
 features:[L('Распознавание лиц и жестов','Face and gesture recognition','人脸与手势识别'),L('Игры в приложении','App-based games','应用游戏'),L('Визуальное программирование','Visual programming','可视化编程')],
 fit:L('Домашнее общение, интерактивные игры и первые шаги в программировании. Не является промышленной платформой.','Home companionship, interactive play and introductory programming. This is not an industrial platform.','适合家庭陪伴、互动游戏与编程入门，并非工业平台。')}
 ];
 return {L,specs,products};
})();
