/* Public category pages share the catalog. */
window.RP.categories = {
  robots: { path: 'technologies/robots/', available: true },
  drones: { path: 'technologies/drones/', available: true },
  components: { path: 'technologies/components/', available: false }
};
const categoryCopy = {
 ru: ['Технологии','Роботы','Дроны и БПЛА','Комплектующие и аксессуары','Категории','Гуманоиды, четвероногие платформы и AI-компаньоны. Описания, фотографии и сравнение моделей.','Дроны DJI для съёмки, бизнеса, промышленности и сельского хозяйства. В каталоге 10 моделей с подробными характеристиками, галереями и ориентировочными ценами для России.','Аксессуары и комплектующие для технологических продуктов. Ассортимент готовится.','Скоро в каталоге','Модели для этого раздела ещё не опубликованы. Расскажите, что вы ищете — обсудим возможность подбора.','Главная','Выберите направление.','Роботы и DJI-дроны уже доступны для изучения. Новые направления будем добавлять по мере формирования ассортимента.'],
 en: ['Technology','Robots','Drones & UAVs','Components & accessories','Categories','Humanoids, quadruped platforms and AI companions. Descriptions, photos and model comparison.','DJI drones for content creation, business, industry and agriculture. Ten models with detailed specifications, galleries and indicative Russian-market pricing.','Accessories and components for technology products. The selection is being prepared.','Coming soon','No models have been published in this category yet. Tell us what you need and we can discuss sourcing options.','Home','Choose a category.','Robots and DJI drones are available now. New categories will grow as the product selection is confirmed.'],
 zh: ['科技产品','机器人','无人机','零部件与配件','产品分类','人形机器人、四足平台与AI陪伴机器人。查看介绍、照片并对比机型。','DJI 无人机适用于影像创作、商业、工业和农业。现有 10 款机型，包含详细参数、图片和俄罗斯市场参考价格。','科技产品的零部件与配件。产品正在筹备中。','即将上线','此分类尚未发布机型。请告诉我们您的需求，我们可以讨论选型与采购方案。','首页','选择产品方向。','机器人与 DJI 无人机现已可以浏览。新分类将随产品选型逐步完善。'],
 it: ['Tecnologia','Robot','Droni e UAV','Componenti e accessori','Categorie','Umanoidi, piattaforme quadrupedi e compagni IA. Descrizioni, foto e confronto tra modelli.','Droni DJI per creazione di contenuti, business, industria e agricoltura. Dieci modelli con specifiche, gallerie e prezzi indicativi per il mercato russo.','Accessori e componenti per prodotti tecnologici. La selezione è in preparazione.','Prossimamente','Non sono ancora stati pubblicati modelli in questa categoria. Raccontaci cosa cerchi per discutere le opzioni di approvvigionamento.','Home','Scegli una categoria.','Robot e droni DJI sono già disponibili. Aggiungeremo nuove categorie man mano che la selezione sarà confermata.'],
 fr: ['Technologie','Robots','Drones et aéronefs sans pilote','Composants et accessoires','Catégories','Humanoïdes, plateformes quadrupèdes et compagnons IA. Descriptions, photos et comparaison des modèles.','Drones DJI pour la création, les entreprises, l’industrie et l’agriculture. Dix modèles avec caractéristiques, galeries et prix indicatifs du marché russe.','Accessoires et composants pour produits technologiques. La sélection est en préparation.','Prochainement','Aucun modèle n’est encore publié dans cette catégorie. Décrivez votre besoin pour discuter des possibilités d’approvisionnement.','Accueil','Choisissez une catégorie.','Les robots et drones DJI sont disponibles. De nouvelles catégories seront enrichies au fur et à mesure de la sélection.'],
 de: ['Technologie','Roboter','Drohnen und UAVs','Komponenten und Zubehör','Kategorien','Humanoide, vierbeinige Plattformen und KI-Begleiter. Beschreibungen, Fotos und Modellvergleich.','DJI-Drohnen für Content, Business, Industrie und Landwirtschaft. Zehn Modelle mit Daten, Galerien und Richtpreisen für den russischen Markt.','Zubehör und Komponenten für Technologieprodukte. Das Sortiment wird vorbereitet.','Demnächst','In dieser Kategorie sind noch keine Modelle veröffentlicht. Beschreiben Sie Ihren Bedarf, damit wir Beschaffungsmöglichkeiten besprechen können.','Startseite','Wählen Sie eine Kategorie.','Roboter und DJI-Drohnen sind verfügbar. Neue Kategorien werden ergänzt, sobald das Sortiment feststeht.'],
 ja: ['テクノロジー','ロボット','ドローン・無人航空機','部品・アクセサリー','カテゴリー','ヒューマノイド、四足歩行プラットフォーム、AIコンパニオン。紹介、写真、モデル比較をご覧ください。','映像制作、ビジネス、産業、農業向けDJIドローン。10モデルの詳細仕様、ギャラリー、ロシア市場の参考価格を掲載。','テクノロジー製品向けの部品・アクセサリー。製品を選定中です。','近日公開','このカテゴリーのモデルはまだ公開されていません。ご希望をお聞かせください。選定・調達についてご相談いただけます。','ホーム','カテゴリーを選ぶ。','ロボットとDJIドローンは現在ご覧いただけます。製品選定に合わせて新しいカテゴリーを充実させていきます。'],
 ko: ['테크놀로지','로봇','드론·무인항공기','부품 및 액세서리','카테고리','휴머노이드, 사족보행 플랫폼 및 AI 반려 로봇. 설명, 사진과 모델 비교를 확인하세요.','콘텐츠 제작, 비즈니스, 산업, 농업용 DJI 드론. 10개 모델의 상세 사양, 갤러리와 러시아 시장 참고 가격을 제공합니다.','기술 제품용 부품과 액세서리. 제품을 준비 중입니다.','출시 예정','아직 이 카테고리에 등록된 모델이 없습니다. 필요한 제품을 알려 주시면 선택과 조달 가능성을 상담해 드립니다.','홈','카테고리를 선택하세요.','로봇과 DJI 드론을 현재 확인할 수 있습니다. 제품 선정이 확정되는 대로 새로운 카테고리를 확장합니다.']
};
for (const [language, values] of Object.entries(categoryCopy)) {
  const keys = ['technology','robots','drones','components','categories','robotsText','dronesText','componentsText','comingSoon','categoryEmpty','home','categoryTitle','categoryText'];
  Object.assign(window.RP.ui[language], Object.fromEntries(keys.map((key,i)=>[key,values[i]])));
}
for (const product of window.RP.products) product.category = 'robots';
