/* Public category pages share the catalog; no placeholder products or prices. */
window.RP.categories = {
  robots: { path: 'technologies/robots/', available: true },
  drones: { path: 'technologies/drones/', available: false },
  components: { path: 'technologies/components/', available: false }
};
const categoryCopy = {
 ru: ['Технологии','Роботы','Дроны и БПЛА','Комплектующие и аксессуары','Категории','Гуманоиды, четвероногие платформы и AI-компаньоны. Описания, фотографии и сравнение моделей.','Гражданские беспилотные летательные аппараты. Ассортимент готовится.','Аксессуары и комплектующие для технологических продуктов. Ассортимент готовится.','Скоро в каталоге','Модели для этого раздела ещё не опубликованы. Расскажите, что вы ищете — обсудим возможность подбора.','Главная','Выберите направление.','Роботы уже доступны для изучения. Новые направления будем добавлять по мере формирования ассортимента.'],
 en: ['Technology','Robots','Drones & UAVs','Components & accessories','Categories','Humanoids, quadruped platforms and AI companions. Descriptions, photos and model comparison.','Civilian unmanned aircraft. The selection is being prepared.','Accessories and components for technology products. The selection is being prepared.','Coming soon','No models have been published in this category yet. Tell us what you need and we can discuss sourcing options.','Home','Choose a category.','Explore the available robots. New categories will grow as the product selection is confirmed.'],
 zh: ['科技产品','机器人','无人机','零部件与配件','产品分类','人形机器人、四足平台与AI陪伴机器人。查看介绍、照片并对比机型。','民用无人机。产品正在筹备中。','科技产品的零部件与配件。产品正在筹备中。','即将上线','此分类尚未发布机型。请告诉我们您的需求，我们可以讨论选型与采购方案。','首页','选择产品方向。','机器人产品已可浏览。新分类将随产品选型的确认逐步完善。'],
 it: ['Tecnologia','Robot','Droni e UAV','Componenti e accessori','Categorie','Umanoidi, piattaforme quadrupedi e compagni IA. Descrizioni, foto e confronto tra modelli.','Aeromobili senza pilota per uso civile. La selezione è in preparazione.','Accessori e componenti per prodotti tecnologici. La selezione è in preparazione.','Prossimamente','Non sono ancora stati pubblicati modelli in questa categoria. Raccontaci cosa cerchi per discutere le opzioni di approvvigionamento.','Home','Scegli una categoria.','Esplora i robot disponibili. Aggiungeremo nuove categorie man mano che la selezione sarà confermata.'],
 fr: ['Technologie','Robots','Drones et aéronefs sans pilote','Composants et accessoires','Catégories','Humanoïdes, plateformes quadrupèdes et compagnons IA. Descriptions, photos et comparaison des modèles.','Aéronefs sans pilote à usage civil. La sélection est en préparation.','Accessoires et composants pour produits technologiques. La sélection est en préparation.','Prochainement','Aucun modèle n’est encore publié dans cette catégorie. Décrivez votre besoin pour discuter des possibilités d’approvisionnement.','Accueil','Choisissez une catégorie.','Découvrez les robots disponibles. De nouvelles catégories seront enrichies au fur et à mesure de la sélection des produits.'],
 de: ['Technologie','Roboter','Drohnen und UAVs','Komponenten und Zubehör','Kategorien','Humanoide, vierbeinige Plattformen und KI-Begleiter. Beschreibungen, Fotos und Modellvergleich.','Unbemannte Luftfahrzeuge für zivile Zwecke. Das Sortiment wird vorbereitet.','Zubehör und Komponenten für Technologieprodukte. Das Sortiment wird vorbereitet.','Demnächst','In dieser Kategorie sind noch keine Modelle veröffentlicht. Beschreiben Sie Ihren Bedarf, damit wir Beschaffungsmöglichkeiten besprechen können.','Startseite','Wählen Sie eine Kategorie.','Entdecken Sie die verfügbaren Roboter. Neue Kategorien werden ergänzt, sobald das Sortiment feststeht.'],
 ja: ['テクノロジー','ロボット','ドローン・無人航空機','部品・アクセサリー','カテゴリー','ヒューマノイド、四足歩行プラットフォーム、AIコンパニオン。紹介、写真、モデル比較をご覧ください。','民生用の無人航空機。製品を選定中です。','テクノロジー製品向けの部品・アクセサリー。製品を選定中です。','近日公開','このカテゴリーのモデルはまだ公開されていません。ご希望をお聞かせください。選定・調達についてご相談いただけます。','ホーム','カテゴリーを選ぶ。','ロボットは現在ご覧いただけます。製品の選定に合わせて新しいカテゴリーを充実させていきます。'],
 ko: ['테크놀로지','로봇','드론·무인항공기','부품 및 액세서리','카테고리','휴머노이드, 사족보행 플랫폼 및 AI 반려 로봇. 설명, 사진과 모델 비교를 확인하세요.','민간용 무인항공기. 제품을 준비 중입니다.','기술 제품용 부품과 액세서리. 제품을 준비 중입니다.','출시 예정','아직 이 카테고리에 등록된 모델이 없습니다. 필요한 제품을 알려 주시면 선택과 조달 가능성을 상담해 드립니다.','홈','카테고리를 선택하세요.','현재 로봇을 살펴볼 수 있습니다. 제품 선정이 확정되는 대로 새로운 카테고리를 확장합니다.']
};
for (const [language, values] of Object.entries(categoryCopy)) {
  const keys = ['technology','robots','drones','components','categories','robotsText','dronesText','componentsText','comingSoon','categoryEmpty','home','categoryTitle','categoryText'];
  Object.assign(window.RP.ui[language], Object.fromEntries(keys.map((key,i)=>[key,values[i]])));
}
for (const product of window.RP.products) product.category = 'robots';
