(() => {
  'use strict';
  const products = window.DJI_CATALOG?.products || [];
  const supported = ['ru','en','zh','it','fr','de','ja','ko'];
  const languageNames = {ru:'Русский',en:'English',zh:'中文',it:'Italiano',fr:'Français',de:'Deutsch',ja:'日本語',ko:'한국어'};
  const ui = {
    ru:{technology:'Технологии',robots:'Роботы',drones:'Дроны и БПЛА',partners:'Партнёры',news:'Новости',title:'Дроны и БПЛА DJI',hero:'10 моделей для съёмки, бизнеса, промышленности и сельского хозяйства. Подробные характеристики, галереи и ориентировочные цены российского рынка.',market:'Цены для рынка России',marketText:'Указаны ориентировочные стартовые цены. Итоговая стоимость зависит от комплектации, курса, наличия, доставки и условий поставки.',catalog:'Каталог DJI',catalogText:'От компактного Neo до промышленных Matrice и агроплатформы Agras.',from:'от',details:'Подробнее',request:'Запросить поставку',back:'Назад к дронам',overview:'Описание',specs:'Характеристики',use:'Применение',weight:'Масса',camera:'Камера',video:'Видео',flight:'Полёт',range:'Передача',protection:'Системы / защита',payload:'Полезная нагрузка',availability:'Цена и наличие подтверждаются менеджером перед заказом.',contactTitle:'Подберём комплектацию и поставку',contactText:'CCCTrade работает из Иу, Китай. Напишите нам модель и желаемую комплектацию — подтвердим цену, наличие и варианты поставки.',copy:'Копировать',copied:'Скопировано',priceNote:'Ориентировочная цена для российского рынка, не публичная оферта.',photo:'Фото',source:'Источник характеристик',all:'Все модели',compact:'Компактные',creator:'Для съёмки',fpv:'FPV',professional:'Профессиональные',enterprise:'Enterprise',cinema:'Кино',agriculture:'Агро'},
    en:{technology:'Technology',robots:'Robots',drones:'Drones & UAVs',partners:'Partners',news:'News',title:'DJI Drones & UAVs',hero:'10 models for content creation, business, industry and agriculture, with detailed specifications, galleries and indicative Russian-market pricing.',market:'Russia-market pricing',marketText:'Prices shown are indicative starting points. Final cost depends on configuration, exchange rates, stock, delivery and supply terms.',catalog:'DJI catalog',catalogText:'From the compact Neo to Matrice enterprise platforms and the Agras agricultural system.',from:'from',details:'View details',request:'Request supply',back:'Back to drones',overview:'Overview',specs:'Specifications',use:'Applications',weight:'Weight',camera:'Camera',video:'Video',flight:'Flight',range:'Transmission',protection:'Systems / protection',payload:'Payload',availability:'Price and availability are confirmed by a manager before ordering.',contactTitle:'We will configure and source your drone',contactText:'CCCTrade operates from Yiwu, China. Send us the model and desired configuration and we will confirm pricing, stock and supply options.',copy:'Copy',copied:'Copied',priceNote:'Indicative Russian-market price, not a public offer.',photo:'Photo',source:'Specification source',all:'All models',compact:'Compact',creator:'Creator',fpv:'FPV',professional:'Professional',enterprise:'Enterprise',cinema:'Cinema',agriculture:'Agriculture'},
    zh:{technology:'科技产品',robots:'机器人',drones:'无人机',partners:'合作伙伴',news:'新闻',title:'DJI 无人机与行业平台',hero:'10 款面向影像创作、商业、工业与农业的 DJI 机型，包含详细参数、图片与俄罗斯市场参考价格。',market:'俄罗斯市场参考价格',marketText:'页面价格为起售价参考。最终价格取决于配置、汇率、库存、物流和供货条件。',catalog:'DJI 产品目录',catalogText:'从轻量 Neo 到 Matrice 行业平台与 Agras 农业无人机。',from:'起',details:'查看详情',request:'咨询供货',back:'返回无人机',overview:'产品介绍',specs:'技术参数',use:'应用场景',weight:'重量',camera:'相机',video:'视频',flight:'飞行',range:'图传',protection:'系统 / 防护',payload:'载荷',availability:'下单前由经理确认最终价格与库存。',contactTitle:'为您确认配置与供货',contactText:'CCCTrade 位于中国义乌。请发送所需机型和配置，我们将确认价格、库存和供货方案。',copy:'复制',copied:'已复制',priceNote:'俄罗斯市场参考价格，不构成公开报价。',photo:'图片',source:'参数来源',all:'全部',compact:'轻量',creator:'影像创作',fpv:'FPV',professional:'专业',enterprise:'行业',cinema:'电影',agriculture:'农业'},
    it:{technology:'Tecnologia',robots:'Robot',drones:'Droni e UAV',partners:'Partner',news:'Notizie',title:'Droni e UAV DJI',hero:'10 modelli per creazione di contenuti, business, industria e agricoltura, con specifiche, gallerie e prezzi indicativi per il mercato russo.',market:'Prezzi indicativi in Russia',marketText:'I prezzi sono indicativi e partono dalla configurazione base. Il costo finale dipende da configurazione, cambio, disponibilità e logistica.',catalog:'Catalogo DJI',catalogText:'Dal compatto Neo alle piattaforme enterprise Matrice e al sistema agricolo Agras.',from:'da',details:'Dettagli',request:'Richiedi fornitura',back:'Torna ai droni',overview:'Panoramica',specs:'Specifiche',use:'Applicazioni',weight:'Peso',camera:'Fotocamera',video:'Video',flight:'Volo',range:'Trasmissione',protection:'Sistemi / protezione',payload:'Carico utile',availability:'Prezzo e disponibilità vengono confermati prima dell’ordine.',contactTitle:'Configuriamo e troviamo il drone giusto',contactText:'CCCTrade opera da Yiwu, Cina. Inviaci modello e configurazione desiderata per confermare prezzo, disponibilità e fornitura.',copy:'Copia',copied:'Copiato',priceNote:'Prezzo indicativo per il mercato russo, non è un’offerta pubblica.',photo:'Foto',source:'Fonte specifiche',all:'Tutti',compact:'Compatti',creator:'Creator',fpv:'FPV',professional:'Professionali',enterprise:'Enterprise',cinema:'Cinema',agriculture:'Agricoltura'},
    fr:{technology:'Technologie',robots:'Robots',drones:'Drones et UAV',partners:'Partenaires',news:'Actualités',title:'Drones et UAV DJI',hero:'10 modèles pour la création, les entreprises, l’industrie et l’agriculture, avec caractéristiques détaillées, galeries et prix indicatifs du marché russe.',market:'Prix indicatifs en Russie',marketText:'Les prix affichés sont des prix de départ indicatifs. Le coût final dépend de la configuration, du taux de change, du stock et de la livraison.',catalog:'Catalogue DJI',catalogText:'Du compact Neo aux plateformes Matrice Enterprise et au système agricole Agras.',from:'à partir de',details:'Voir le détail',request:'Demander une offre',back:'Retour aux drones',overview:'Présentation',specs:'Caractéristiques',use:'Applications',weight:'Poids',camera:'Caméra',video:'Vidéo',flight:'Vol',range:'Transmission',protection:'Systèmes / protection',payload:'Charge utile',availability:'Prix et disponibilité confirmés avant commande.',contactTitle:'Nous configurons et sourçons votre drone',contactText:'CCCTrade opère depuis Yiwu, Chine. Envoyez le modèle et la configuration souhaitée pour confirmer prix, stock et options de livraison.',copy:'Copier',copied:'Copié',priceNote:'Prix indicatif du marché russe, non contractuel.',photo:'Photo',source:'Source des spécifications',all:'Tous',compact:'Compacts',creator:'Création',fpv:'FPV',professional:'Professionnels',enterprise:'Enterprise',cinema:'Cinéma',agriculture:'Agriculture'},
    de:{technology:'Technologie',robots:'Roboter',drones:'Drohnen & UAVs',partners:'Partner',news:'News',title:'DJI Drohnen & UAVs',hero:'10 Modelle für Content, Business, Industrie und Landwirtschaft mit detaillierten Daten, Galerien und Richtpreisen für den russischen Markt.',market:'Richtpreise in Russland',marketText:'Die Preise sind unverbindliche Startpreise. Der Endpreis hängt von Konfiguration, Wechselkurs, Lagerbestand, Lieferung und Lieferbedingungen ab.',catalog:'DJI Katalog',catalogText:'Von der kompakten Neo bis zu Matrice-Enterprise-Plattformen und dem Agras-Agrarsystem.',from:'ab',details:'Details',request:'Lieferung anfragen',back:'Zurück zu Drohnen',overview:'Übersicht',specs:'Spezifikationen',use:'Anwendungen',weight:'Gewicht',camera:'Kamera',video:'Video',flight:'Flug',range:'Übertragung',protection:'Systeme / Schutz',payload:'Nutzlast',availability:'Preis und Verfügbarkeit werden vor der Bestellung bestätigt.',contactTitle:'Wir konfigurieren und beschaffen Ihre Drohne',contactText:'CCCTrade arbeitet aus Yiwu, China. Senden Sie Modell und gewünschte Konfiguration für Preis-, Bestands- und Lieferbestätigung.',copy:'Kopieren',copied:'Kopiert',priceNote:'Unverbindlicher Richtpreis für den russischen Markt.',photo:'Foto',source:'Spezifikationsquelle',all:'Alle',compact:'Kompakt',creator:'Creator',fpv:'FPV',professional:'Professional',enterprise:'Enterprise',cinema:'Cinema',agriculture:'Agrar'},
    ja:{technology:'テクノロジー',robots:'ロボット',drones:'ドローン・UAV',partners:'パートナー',news:'ニュース',title:'DJI ドローン・UAV',hero:'映像制作、ビジネス、産業、農業向け10モデル。詳細仕様、ギャラリー、ロシア市場の参考価格を掲載。',market:'ロシア市場の参考価格',marketText:'表示価格は参考となる開始価格です。最終価格は構成、為替、在庫、配送条件により変動します。',catalog:'DJI カタログ',catalogText:'コンパクトなNeoからMatrice業務用プラットフォーム、Agras農業システムまで。',from:'約',details:'詳細を見る',request:'供給を相談',back:'ドローン一覧へ',overview:'概要',specs:'仕様',use:'用途',weight:'重量',camera:'カメラ',video:'動画',flight:'飛行',range:'伝送',protection:'システム / 保護',payload:'ペイロード',availability:'価格と在庫は注文前に担当者が確認します。',contactTitle:'構成と供給をご案内します',contactText:'CCCTradeは中国・義烏を拠点にしています。希望モデルと構成をお送りください。価格、在庫、供給方法を確認します。',copy:'コピー',copied:'コピーしました',priceNote:'ロシア市場の参考価格であり、公開オファーではありません。',photo:'写真',source:'仕様出典',all:'すべて',compact:'コンパクト',creator:'クリエイター',fpv:'FPV',professional:'プロ',enterprise:'業務用',cinema:'シネマ',agriculture:'農業'},
    ko:{technology:'테크놀로지',robots:'로봇',drones:'드론·UAV',partners:'파트너',news:'뉴스',title:'DJI 드론 & UAV',hero:'콘텐츠 제작, 비즈니스, 산업, 농업용 10개 모델. 상세 사양, 갤러리와 러시아 시장 참고 가격을 제공합니다.',market:'러시아 시장 참고 가격',marketText:'표시 가격은 참고 시작가입니다. 최종 가격은 구성, 환율, 재고, 배송 및 공급 조건에 따라 달라집니다.',catalog:'DJI 카탈로그',catalogText:'소형 Neo부터 Matrice 엔터프라이즈 플랫폼과 Agras 농업 시스템까지.',from:'부터',details:'상세 보기',request:'공급 문의',back:'드론으로 돌아가기',overview:'개요',specs:'사양',use:'용도',weight:'무게',camera:'카메라',video:'비디오',flight:'비행',range:'전송',protection:'시스템 / 보호',payload:'페이로드',availability:'가격과 재고는 주문 전 담당자가 확인합니다.',contactTitle:'구성과 공급을 도와드립니다',contactText:'CCCTrade는 중국 이우에서 운영합니다. 원하는 모델과 구성을 보내주시면 가격, 재고, 공급 옵션을 확인합니다.',copy:'복사',copied:'복사됨',priceNote:'러시아 시장 참고 가격이며 공개 제안이 아닙니다.',photo:'사진',source:'사양 출처',all:'전체',compact:'컴팩트',creator:'크리에이터',fpv:'FPV',professional:'프로',enterprise:'엔터프라이즈',cinema:'시네마',agriculture:'농업'}
  };
  const esc = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const params = new URLSearchParams(location.search);
  let saved=''; try{saved=JSON.parse(localStorage.getItem('robotics_pro_language')||'""')}catch{}
  let lang = params.get('lang') || saved || 'ru'; if(!supported.includes(lang)) lang='ru';
  const text = value => typeof value === 'object' ? (value[lang] || value.en || value.ru || '') : value;
  const money = value => new Intl.NumberFormat({ru:'ru-RU',en:'en-US',zh:'zh-CN',it:'it-IT',fr:'fr-FR',de:'de-DE',ja:'ja-JP',ko:'ko-KR'}[lang],{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(value);
  const currentWords = () => ui[lang];
  const withLang = path => { const u=new URL(path,location.href); u.searchParams.set('lang',lang); return u.pathname+u.search+u.hash; };
  const contactValue = 'DJI / CCCTrade\nTelegram: @CheliUsNick\nEmail: helloitisnick@gmail.com\nPhone: +7 952 082-45-39';
  const isProduct = location.pathname.endsWith('/product.html');
  const id = params.get('product');
  const product = products.find(p=>p.id===id);
  let filter='all';

  function header(){const w=currentWords();return `<header class="dji-header"><a class="dji-brand" href="${withLang('./index.html')}">CCCTrade</a><nav class="dji-nav"><a href="${withLang('./technologies/')}">${w.technology}</a><a href="${withLang('./technologies/robots/')}">${w.robots}</a><a href="${withLang('./technologies/drones/')}">${w.drones}</a><a href="${withLang('./partners.html')}">${w.partners}</a><a href="${withLang('./news.html')}">${w.news}</a></nav><div class="dji-tools"><label class="dji-language"><select id="djiLanguage" aria-label="Language">${supported.map(code=>`<option value="${code}" ${code===lang?'selected':''}>${languageNames[code]}</option>`).join('')}</select></label></div></header>`}
  function card(p){const w=currentWords();return `<article class="dji-card"><a class="dji-card-media" href="${withLang(`./technologies/drones/product.html?product=${p.id}`)}"><img src="${p.images[0]}" alt="${esc(p.name)}" loading="lazy" referrerpolicy="no-referrer"></a><div class="dji-card-copy"><div class="dji-card-top"><div><span class="dji-badge">${esc(w[p.segment]||p.segment)}</span><h3><a href="${withLang(`./technologies/drones/product.html?product=${p.id}`)}">${esc(p.name)}</a></h3></div><div class="dji-card-price">${w.from} ${money(p.price)}</div></div><p>${esc(text(p.tagline))}</p><div class="dji-card-actions"><a class="dji-btn" href="${withLang(`./technologies/drones/product.html?product=${p.id}`)}">${w.details} ↗</a><button class="dji-btn secondary" data-request="${p.id}">${w.request}</button></div></div></article>`}
  function catalogPage(){const w=currentWords();const visible=filter==='all'?products:products.filter(p=>p.segment===filter);return `${header()}<main><section class="dji-hero"><div><span class="dji-kicker">CCCTrade · DJI · Yiwu, China</span><h1>${w.title}</h1><p>${w.hero}</p></div><aside class="dji-price-note"><strong>${w.market}</strong><span>${w.marketText}</span></aside></section><section class="dji-section"><div class="dji-section-head"><div><span class="dji-kicker">DJI / 10 MODELS</span><h2>${w.catalog}</h2></div><p>${w.catalogText}</p></div><div class="dji-card-actions" style="margin:0 0 28px">${['all','compact','creator','fpv','professional','enterprise','cinema','agriculture'].map(k=>`<button class="dji-btn ${filter===k?'':'secondary'}" data-filter="${k}">${w[k]}</button>`).join('')}</div><div class="dji-grid" id="djiGrid">${visible.map(card).join('')}</div><p class="dji-note" style="margin-top:24px">${w.priceNote}</p></section>${contactBlock()}</main>${footer()}`}
  function specRows(p){const w=currentWords();const labels={weight:w.weight,camera:w.camera,video:w.video,flight:w.flight,range:w.range,protection:w.protection,payload:w.payload};return Object.entries(p.specs).map(([k,v])=>`<tr><th>${labels[k]||k}</th><td>${esc(v)}</td></tr>`).join('')}
  function productPage(){const w=currentWords();if(!product)return `${header()}<main class="dji-empty"><h1>404</h1><p>Product not found.</p><a class="dji-btn" href="${withLang('./technologies/drones/')}">${w.back}</a></main>${footer()}`;return `${header()}<main><section class="dji-product"><nav class="dji-breadcrumbs"><a href="${withLang('./index.html')}">CCCTrade</a><span>/</span><a href="${withLang('./technologies/drones/')}">${w.drones}</a><span>/</span><span>${esc(product.name)}</span></nav><div class="dji-product-layout"><div><div class="dji-gallery-stage"><img id="djiMainPhoto" src="${product.images[0]}" alt="${esc(product.name)}" referrerpolicy="no-referrer"></div><div class="dji-thumbs">${product.images.map((src,i)=>`<button class="dji-thumb ${i===0?'active':''}" data-photo="${i}"><img src="${src}" alt="${esc(product.name)} — ${w.photo} ${i+1}" loading="lazy" referrerpolicy="no-referrer"></button>`).join('')}</div></div><div class="dji-info"><span class="dji-badge">DJI · ${esc(w[product.segment]||product.segment)}</span><h1>${esc(product.name)}</h1><h2>${esc(text(product.tagline))}</h2><p class="lead">${esc(text(product.description))}</p><div class="dji-price"><div><small>${w.from}</small><strong>${money(product.price)}</strong></div><span class="dji-badge">${w.request}</span></div><div class="dji-card-actions"><button class="dji-btn" data-request="${product.id}">${w.request} ↗</button><a class="dji-btn secondary" href="${withLang('./technologies/drones/')}">← ${w.back}</a></div><p class="dji-note">${w.availability}<br>${w.priceNote}</p><div class="dji-order-panel" id="orderPanel" hidden></div></div></div></section><section class="dji-details"><div class="dji-detail-grid"><div><span class="dji-kicker">01 / ${w.overview}</span><h2>${w.overview}</h2></div><div><p>${esc(text(product.description))}</p><p><strong>${w.use}:</strong> ${esc(text(product.use))}</p></div></div><div class="dji-detail-grid"><div><span class="dji-kicker">02 / ${w.specs}</span><h2>${w.specs}</h2></div><div><table class="dji-specs"><tbody>${specRows(product)}</tbody></table><p class="dji-note"><a href="${product.source}" target="_blank" rel="noopener">${w.source}: DJI ↗</a></p></div></div></section>${contactBlock()}</main>${footer()}`}
  function contactBlock(){const w=currentWords();return `<section class="dji-contact"><div><span class="dji-kicker">CCCTrade · Yiwu, China</span><h2>${w.contactTitle}</h2><p>${w.contactText}</p></div><button class="dji-btn" data-copy-contact>${w.copy}</button></section>`}
  function footer(){return `<footer class="dji-footer"><strong>CCCTrade</strong><span>Yiwu, China · helloitisnick@gmail.com · +7 952 082-45-39</span><span>© ${new Date().getFullYear()}</span></footer>`}
  function render(){document.documentElement.lang=lang==='zh'?'zh-CN':lang;document.body.className='dji-shell';document.querySelector('#app').innerHTML=isProduct?productPage():catalogPage();document.title=isProduct&&product?`${product.name} — CCCTrade`:`${currentWords().title} — CCCTrade`;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=isProduct&&product?text(product.description):currentWords().hero}
  function showRequest(id){const p=products.find(x=>x.id===id);const w=currentWords();const panel=document.querySelector('#orderPanel');const txt=`${p?.name||'DJI'}\n${w.from} ${p?money(p.price):''}\nTelegram: @CheliUsNick\nEmail: helloitisnick@gmail.com\nPhone: +7 952 082-45-39`;if(panel){panel.hidden=false;panel.innerHTML=`<strong>${esc(p.name)}</strong><p>${esc(w.availability)}</p><p>Telegram: @CheliUsNick<br>Email: helloitisnick@gmail.com<br>Phone: +7 952 082-45-39</p><button class="dji-btn secondary" data-copy-value="${esc(txt)}">${w.copy}</button>`;panel.scrollIntoView({behavior:'smooth',block:'nearest'})}else{navigator.clipboard?.writeText(txt).catch(()=>{});alert(`${w.contactTitle}\n\nTelegram: @CheliUsNick\nEmail: helloitisnick@gmail.com\nPhone: +7 952 082-45-39`)} }
  document.addEventListener('change',e=>{if(e.target.id==='djiLanguage'){lang=e.target.value;localStorage.setItem('robotics_pro_language',JSON.stringify(lang));const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);render()}});
  document.addEventListener('click',async e=>{const photo=e.target.closest('[data-photo]');if(photo&&product){const i=Number(photo.dataset.photo);document.querySelector('#djiMainPhoto').src=product.images[i];document.querySelectorAll('.dji-thumb').forEach((b,n)=>b.classList.toggle('active',n===i));return}const filterButton=e.target.closest('[data-filter]');if(filterButton){filter=filterButton.dataset.filter;render();return}const req=e.target.closest('[data-request]');if(req){showRequest(req.dataset.request);return}const copy=e.target.closest('[data-copy-contact],[data-copy-value]');if(copy){const value=copy.dataset.copyValue||contactValue;try{await navigator.clipboard.writeText(value);copy.textContent=currentWords().copied;setTimeout(()=>copy.textContent=currentWords().copy,1400)}catch{} } });
  render();
})();
